export interface Article {
  id: string;
  title: string;
  source: string;
  category: "DeFi" | "Layer2" | "AI" | "Regulation" | "Markets" | "Infrastructure";
  summary: string;
  content: string;
  timestamp: string;
  readTime: number;
  tags: string[];
  trending: boolean;
  sentiment: "bullish" | "bearish" | "neutral";
  url: string;
}

export const MOCK_ARTICLES: Article[] = [
  {
    id: "1",
    title: "Base Network Hits 10M Daily Transactions as Coinbase Doubles L2 Infrastructure Bet",
    source: "cryptonewsorg.com",
    category: "Layer2",
    summary: "Coinbase's Base network has crossed 10 million daily transactions, cementing its position as the highest-throughput Ethereum L2. The milestone arrives as Coinbase announces $500M in additional infrastructure investment.",
    content: "",
    timestamp: "2026-06-01T08:30:00Z",
    readTime: 4,
    tags: ["Base", "Coinbase", "Layer2"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "2",
    title: "SEC Drops Long-Running Uniswap Investigation After Congressional Crypto Framework Passes",
    source: "cryptonewsorg.com",
    category: "Regulation",
    summary: "The SEC formally closed its investigation into Uniswap Labs following the passage of the Digital Asset Market Structure Act.",
    content: "",
    timestamp: "2026-06-01T07:15:00Z",
    readTime: 5,
    tags: ["SEC", "Uniswap", "Regulation"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "3",
    title: "Ethereum's EIP-7935 Slashes State Growth by 60%—Devs Target September Fork",
    source: "cryptonewsorg.com",
    category: "Infrastructure",
    summary: "A new EIP targeting Ethereum's state bloat problem has passed ACD review with rough consensus. If shipped in the Osaka hard fork, it would dramatically reduce the cost of running full nodes.",
    content: "",
    timestamp: "2026-06-01T06:45:00Z",
    readTime: 6,
    tags: ["Ethereum", "EIP", "Infrastructure"],
    trending: false,
    sentiment: "neutral",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "4",
    title: "BlackRock's On-Chain Treasury Fund Crosses $8B AUM—Wall Street's DeFi Pivot Accelerates",
    source: "cryptonewsorg.com",
    category: "DeFi",
    summary: "BUIDL, BlackRock's tokenized treasury fund on Ethereum, has surpassed $8 billion in assets under management, making it the largest tokenized real-world asset vehicle ever.",
    content: "",
    timestamp: "2026-05-31T20:00:00Z",
    readTime: 5,
    tags: ["BlackRock", "RWA", "DeFi"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "5",
    title: "Anthropic Releases Claude 4.8 with 2M Context Window and Native Code Execution",
    source: "cryptonewsorg.com",
    category: "AI",
    summary: "Anthropic's latest model ships with a 2-million token context window and sandboxed code execution built directly into the base model. Benchmarks show 40% improvement on agentic tasks.",
    content: "",
    timestamp: "2026-05-31T16:30:00Z",
    readTime: 4,
    tags: ["Anthropic", "Claude", "AI"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "6",
    title: "MakerDAO's $500M ETH Collateral Liquidation Triggers Flash Crash Below $3,200",
    source: "cryptonewsorg.com",
    category: "Markets",
    summary: "A large forced liquidation of ETH collateral in MakerDAO's Spark protocol caused a 7-minute flash crash on centralized exchanges.",
    content: "",
    timestamp: "2026-05-31T11:20:00Z",
    readTime: 5,
    tags: ["MakerDAO", "ETH", "DeFi"],
    trending: false,
    sentiment: "bearish",
    url: "https://cryptonewsorg.com",
  },
];

// Pool of "new" articles injected on refresh — newest first
export const REFRESH_POOL: Article[] = [
  {
    id: "r1",
    title: "Solana DEX Volume Surpasses Ethereum for Third Consecutive Month",
    source: "cryptonewsorg.com",
    category: "Markets",
    summary: "On-chain data shows Solana-based DEXs processed $48B in volume during May, outpacing Ethereum's $41B for the third month running. Jupiter and Raydium account for the majority of the gap.",
    content: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    readTime: 4,
    tags: ["Solana", "DEX", "Markets"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "r2",
    title: "Circle Files for NASDAQ IPO, Values USDC Business at $18B",
    source: "cryptonewsorg.com",
    category: "Regulation",
    summary: "Circle Internet Financial has filed an S-1 with the SEC, seeking a valuation of approximately $18 billion. The filing highlights USDC's $44B circulation and growing institutional reserve management revenue.",
    content: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    readTime: 5,
    tags: ["Circle", "USDC", "IPO"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "r3",
    title: "OpenAI Ships GPT-5 with Real-Time Web Browsing and Persistent Memory",
    source: "cryptonewsorg.com",
    category: "AI",
    summary: "GPT-5 launches with native real-time web access and cross-session memory baked in. Early benchmarks put it 22% ahead of Claude 4.8 on reasoning tasks, though Anthropic disputes the methodology.",
    content: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    readTime: 5,
    tags: ["OpenAI", "GPT-5", "AI"],
    trending: true,
    sentiment: "neutral",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "r4",
    title: "Arbitrum DAO Votes to Deploy $200M Treasury Into On-Chain Yield Strategies",
    source: "cryptonewsorg.com",
    category: "DeFi",
    summary: "ARB token holders approved AIP-75 with 71% support, authorizing the foundation to deploy $200M from its treasury into a diversified on-chain yield portfolio managed by a newly formed financial committee.",
    content: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    readTime: 4,
    tags: ["Arbitrum", "DAO", "DeFi"],
    trending: false,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "r5",
    title: "Nvidia H300 GPUs Begin Shipping—AI Training Costs Drop 40% Overnight",
    source: "cryptonewsorg.com",
    category: "Infrastructure",
    summary: "Nvidia's H300 GPU, successor to the H100, began shipping to hyperscalers this week. Early benchmarks show a 2.4x throughput improvement for transformer training workloads, implying a ~40% reduction in per-token compute cost.",
    content: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    readTime: 4,
    tags: ["Nvidia", "GPU", "AI"],
    trending: true,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
  {
    id: "r6",
    title: "Polygon zkEVM Achieves EVM Equivalence Milestone, Targets Full Mainnet in Q3",
    source: "cryptonewsorg.com",
    category: "Layer2",
    summary: "Polygon's zkEVM has passed a comprehensive EVM equivalence test suite, clearing the final technical hurdle before full mainnet launch targeted for Q3 2026.",
    content: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    readTime: 3,
    tags: ["Polygon", "zkEVM", "Layer2"],
    trending: false,
    sentiment: "bullish",
    url: "https://cryptonewsorg.com",
  },
];
